-- Idempotent creation endpoint for the web offline queue.
--
-- This is deliberately NOT an extension of save_manual_cost: recurring costs
-- create a series and future rows, while edits have conflict semantics that an
-- offline client cannot safely reconstruct.  This endpoint creates only one
-- non-recurring manual row, with the UUID generated by the browser.
create or replace function public.create_manual_cost_idempotent(
  p_id          uuid,
  p_description text,
  p_type        text,
  p_category    text,
  p_amount      numeric,
  p_cost_date   date
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_tenant  uuid;
  v_existing public.costs%rowtype;
  v_created uuid;
begin
  v_tenant := public.current_tenant_id();
  if v_tenant is null then
    raise exception using errcode = '42501', message = 'sem empresa na sessão';
  end if;
  if not public.current_actor_can_use_module('costs') then
    raise exception using errcode = '42501', message = 'sem permissão para custos';
  end if;

  if p_id is null then
    raise exception using errcode = '22023', message = 'identificador do custo é obrigatório';
  end if;
  p_description := nullif(btrim(p_description), '');
  p_category := nullif(btrim(p_category), '');
  if p_description is null then
    raise exception using errcode = '22023', message = 'escreva o que foi o gasto';
  end if;
  if p_type is null or p_type not in ('fixed', 'variable') then
    raise exception using errcode = '22023', message = 'tipo de custo inválido';
  end if;
  if p_amount is null or p_amount <= 0 or p_amount::text in ('NaN', 'Infinity', '-Infinity') then
    raise exception using errcode = '22023', message = 'informe um valor maior que zero';
  end if;
  if p_cost_date is null then
    raise exception using errcode = '22023', message = 'informe a data do custo';
  end if;

  insert into public.costs (
    id, tenant_id, user_id, description, type, category, amount,
    is_recurring, origin, cost_date, recurrence_id, competence
  ) values (
    p_id, v_tenant, auth.uid(), p_description, p_type, p_category, p_amount,
    false, 'manual', p_cost_date, null, null
  )
  on conflict (id) do nothing
  returning id into v_created;

  if v_created is not null then
    return jsonb_build_object('id', v_created, 'created', true);
  end if;

  -- A concurrent retry waits on the primary-key index above. At READ COMMITTED
  -- this following statement sees the committed winner. Only an exact replay
  -- is success: an accidental/cross-tenant UUID collision must remain visible.
  select c.* into v_existing
    from public.costs c
   where c.id = p_id;

  if found
     and v_existing.tenant_id = v_tenant
     and v_existing.user_id is not distinct from auth.uid()
     and v_existing.description = p_description
     and v_existing.type = p_type
     and v_existing.category is not distinct from p_category
     and v_existing.amount = p_amount
     and v_existing.cost_date = p_cost_date
     and v_existing.origin = 'manual'
     and not v_existing.is_recurring
     and v_existing.recurrence_id is null
     and v_existing.competence is null then
    return jsonb_build_object('id', p_id, 'created', false);
  end if;

  raise exception using
    errcode = '23505',
    message = 'identificador já usado por outro custo';
end;
$$;

revoke all on function public.create_manual_cost_idempotent(uuid, text, text, text, numeric, date)
  from public, anon;
grant execute on function public.create_manual_cost_idempotent(uuid, text, text, text, numeric, date)
  to authenticated;

comment on function public.create_manual_cost_idempotent(uuid, text, text, text, numeric, date) is
  'Creates one manual non-recurring cost. Exact retries with the same client UUID are idempotent; mismatched UUID reuse is rejected.';
